# Fly.io Configuration for WAHA

app = "kabowd-waha"
primary_region = "cdg"

[build]
dockerfile = "./waha/Dockerfile"

[env]
PORT = "3000"
WHATSAPP_DEFAULT_ENGINE = "NOWEB"
WAHA_SESSION_NAME = "default"
WHATSAPP_START_SESSION = "default"
WAHA_RESTART_ALL_SESSIONS = "true"
WHATSAPP_SESSION_NOT_START_AND_WAIT = "true"
WAHA_BROWSER_HEADLESS = "true"
WAHA_PRINT_QR = "true"
WAHA_HOOK_EVENTS = "message,message.reaction,presence.update,chat.update"
WAHA_MEDIA_STORAGE = "local"
WAHA_LOCAL_STORE_BASE_DIR = "/var/lib/waha/storage"
WHATSAPP_FILES_FOLDER = "/app/whatsapp_files"
WHATSAPP_FILES_LIFETIME = "86400"
WAHA_LOG_FORMAT = "json"
WAHA_LOG_LEVEL = "info"
WAHA_DASHBOARD_ENABLED = "true"
WAHA_DASHBOARD_USERNAME = "admin_waha"

[[services]]
internal_port = 3000
processes = ["app"]
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1